# Generated by Django 4.2.9 on 2026-02-22 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=20)),
                ('loan_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('records_fetched', models.IntegerField(default=0, help_text='Number of records fetched from bank')),
                ('records_valid', models.IntegerField(default=0, help_text='Number of records passing validation')),
                ('records_invalid', models.IntegerField(default=0, help_text='Number of records failing validation')),
                ('version_before', models.IntegerField(blank=True, help_text='Version before sync', null=True)),
                ('version_after', models.IntegerField(blank=True, help_text='Version after sync', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if sync failed')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text='Unique tenant identifier (e.g., BANK001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable bank name', max_length=200)),
                ('api_key', models.CharField(db_index=True, default=uuid.uuid4, help_text='API key for authentication and tenant isolation', max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant is active')),
                ('loan_types', models.JSONField(default=list, help_text="List of loan types this tenant has (e.g., ['RETAIL', 'COMMERCIAL'])")),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tenant_id'],
            },
        ),
        migrations.CreateModel(
            name='ValidationErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(help_text='Row number in the source data', null=True)),
                ('field_name', models.CharField(help_text='Name of the field that failed validation', max_length=100)),
                ('error_type', models.CharField(help_text='Type of validation error', max_length=50)),
                ('error_message', models.CharField(help_text='Human-readable error description', max_length=500)),
                ('raw_value', models.CharField(blank=True, help_text='Original value that failed validation', max_length=500)),
                ('sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_errors', to='tenants.synclog')),
            ],
            options={
                'ordering': ['row_number', 'field_name'],
            },
        ),
        migrations.AddField(
            model_name='synclog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(help_text='Data file type: loans or payments', max_length=20)),
                ('loan_type', models.CharField(help_text='Loan type: RETAIL or COMMERCIAL', max_length=20)),
                ('last_version', models.IntegerField(default=0, help_text='Last synced version number')),
                ('last_checksum', models.CharField(blank=True, help_text='Last synced data checksum', max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_states', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant', 'file_type', 'loan_type'],
                'unique_together': {('tenant', 'file_type', 'loan_type')},
            },
        ),
    ]
